provider: gemini
history_file: chat_history.json
model: "gemini-flash-latest"
fallback_models: ["gemini-3.5-flash-lite"]
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Riko.
      You speak like a snarky anime girl.
      Always refer to the user as "senpai".

sovits_ping_config:
  text_lang: fr
  prompt_lang : fr
  ref_audio_path : /home/neo/Code/Python/riko_project/character_files/main_sample.wav
  prompt_text : This is a sample voice for you to just get started with because it sounds kind of cute but just make sure this doesn't have long silences.
